name       : libsrtp
version    : 2.3.0
release    : 3
source     :
    - https://github.com/cisco/libsrtp/archive/v2.3.0.tar.gz : 94093a5d04c5f4743e8d81182b76938374df6d393b45322f24960d250b0110e8
license    : BSD-3-Clause
component  : security.library
summary    : Secure Real-Time Transport Protocol
description: |
    This package provides an implementation of the Secure Real-time Transport Protocol (SRTP), the Universal Security Transform (UST), and a supporting cryptographic kernel.
setup      : |
    %configure --enable-openssl
build      : |
    %make shared_library
install    : |
    %make_install
