name       : libsrtp
version    : 2.1.0
release    : 2
source     :
    - https://github.com/cisco/libsrtp/archive/v2.1.0.tar.gz : 0302442ed97d34a77abf84617b657e77674bdd8e789d649f1cac0c5f0d0cf5ee
license    : BSD-3-Clause
component  : security
summary    : Secure Real-Time Transport Protocol
description: |
    This package provides an implementation of the Secure Real-time Transport Protocol (SRTP), the Universal Security Transform (UST), and a supporting cryptographic kernel.
builddeps  :
    - pkgconfig(openssl)
setup      : |
    %configure --enable-openssl
build      : |
    %make shared_library
install    : |
    %make_install
