name       : libsrtp 
version    : 2.0.0
release    : 1
source     :
    - https://github.com/cisco/libsrtp/archive/v2.0.0.tar.gz : 2296d132fd8cadd691d1fffeabbc1b9c42ec09e9e780a0d9bd8234a98e63a5a1
license    : BSD-3-Clause 
component  : security 
summary    : Secure Real-Time Transport Protocol 
description: |
    This package provides an implementation of the Secure Real-time Transport Protocol (SRTP), the Universal Security Transform (UST), and a supporting cryptographic kernel.
builddeps  :
    - pkgconfig(openssl)
setup      : |
    %configure --enable-openssl
build      : |
    %make shared_library
install    : |
    %make_install
